### ISSUE TITLE
repository lacks all data files

### ISSUE THREAD

**Issue by three-old-coders** [xlejx-rodsxn/sar_migration#1]
The source code contains hardcoded paths like "c://whatever" and references many data files not part of the repo.
Can you add these missing files, too?

**Comment by xlejx-rodsxn** [comment]
Please read the paper https://www.nature.com/articles/s41598-023-38119-4 for which this code was written, particularly the data availability statement. There is a reason why the files aren't uploaded (we aren't allowed to do that due to proprietary data restrictions) and why we would never upload the files. If you want to make a formal request of the data used to the study for replication purposes (possible), please make sure to make a formal request to the email given in the paper.

**Comment by TilmannF** [comment]
By exposing your local file path structure, you've already exposed which cloud storage solution you're using. You've exposed yourself & your organization to an unnecessary risk. This is something that happened to almost all of us, but shouldn't be the case in a professional environment which I suspect academia is.

One starting point for improvement could be this StackOverflow thread: https://stackoverflow.com/questions/24392924/what-is-a-way-to-manage-paths-to-local-files-outside-a-git-repository-without-cl

Furthermore publishing software on an open source platform & not disclosing how to actually run the software with proper data input might be considered rude & amateurish by some.

**Comment by xlejx-rodsxn** [comment]
Thanks for poining that out. I will take it into consideration for another time. I would call myself then a proud amateur (no offense taken) ;)

**Comment by xlejx-rodsxn** [comment]
Data is now available here https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SOBJDU&faces-redirect=true
